// lessons list for the website
var lessons = [
  {
    "id": "L001",
    "subject": "Math",
    "location": "London",
    "price": 100,
    "space": 5,
    "image": "images/maths.jpg",
    "rating":3,
  },
  {
    "id": "L002",
    "subject": "Science",
    "location": "Ofxord",
    "price": 150,
    "space": 5,
    "image": "images/science.jpg",
    "rating":1,
  },
  {
    "id": "L003",
    "subject": "Basket Ball",
    "location": "York",
    "price": 190,
    "space": 5,
    "image": "images/basketball.jpg",
    "rating":5,
  },
  {
    "id": "L004",
    "subject": "Music",
    "location": "Bristol",
    "price": 120,
    "space": 5,
    "image": "images/music.jpg",
    "rating":4,
  },
  {
    "id": "L005",
    "subject": "Book Reading",
    "location": "Lanchester",
    "price": 110,
    "space": 5,
    "image": "images/reading.jpg",
    "rating":5,
  },
  {
    "id": "L006",
    "subject": "Photography",
    "location": "Oxford",
    "price": 170,
    "space": 5,
    "image": "images/photography.jpg",
    "rating":1,
  },
  {
    "id": "L007",
    "subject": "Volley Ball",
    "location": "London",
    "price": 145,
    "space": 5,
    "image": "images/volleyball.jpg",
    "rating":2,
  },
  {
    "id": "L008",
    "subject": "Art and Craft",
    "location": "Lanchester",
    "price": 100,
    "space": 5,
    "image": "images/art.jpg",
    "rating":3,
  },
  {
    "id": "L009",
    "subject": "Baseball",
    "location": "London",
    "price": 190,
    "space": 5,
    "image": "images/baseball.jpg",
    "rating":5,
  },
  {
    "id": "L010",
    "subject": "Culinary",
    "location": "Bristol",
    "price": 150,
    "space": 5,
    "image": "images/culinary.jpg",
    "rating":4,
  }

];
